### ISSUE TITLE
Asgaros Forum: Change "Banned" to "Paused" and "Ban" to "Pause"

### ISSUE THREAD

**Issue by Carewen** [IAMOWN/SynthesisOfLight#8]
There is a need to be able to pause an account from posting. This will lead to the following outcomes:

An account can be paused by going to: https://synthesisoflight.com/forum/members/
- A Moderator/Administrator can then click on the member to be paused
- They can currently "Ban User". This will need to be changed to "Pause User"
- When Paused the user profile will display the link "Unpause User" (changed from Unban User)
- Wherever the paused user account appears with a post (Topic or Reply) the word "Paused" will replaced "Banned"

There are other potential refinements for Administrators:

- User dashboard: https://synthesisoflight.com/wp-admin/users.php
- Forum Roles > Banned changed to Paused

This may be a moderately complex change. We need to analyze.

**Comment by exvitorino** [comment]
Forum files updated to relabel "Banned" to "Paused".
forum-memberslist.php
forum-permissions.php
forum-profile.php
